#ifndef PIC_IDS_H
#define PIC_IDS_H

#define PIC_ID_BOOTSPLASH (0)
#define PIC_ID_OIL_PRESSURE (1)
#define PIC_ID_OIL_TEMP (2)
#define PIC_ID_WATER_TEMP (3)
#define PIC_ID_BLOCK_TEMP (4)
#define PIC_ID_FUEL_PRESSURE (5)
#define PIC_ID_FUEL_TEMP (6)
#define PIC_ID_BATTERY (7)
#define PIC_ID_OIL_TEMP_LOW (8)
#define PIC_ID_SPEAKER (9)
#define PIC_ID_UPSHIFT_BTN (10)
#define PIC_ID_DOWNSHIFT_BTN (11)
#define PIC_ID_MICROPHONE (12)
#define PIC_ID_GEAR_PARK (13)
#define PIC_ID_GEAR_REVERSE (14)
#define PIC_ID_GEAR_NEUTRAL (15)
#define PIC_ID_GEAR_DRIVE (16)
#define PIC_ID_GEAR_0 (17)
#define PIC_ID_GEAR_1 (18)
#define PIC_ID_GEAR_2 (19)
#define PIC_ID_GEAR_3 (20)
#define PIC_ID_GEAR_4 (21)
#define PIC_ID_GEAR_5 (22)
#define PIC_ID_GEAR_6 (23)
#define PIC_ID_GEAR_7 (24)

#endif
